sudo: false
language: python
python:
  - 3.5
install: pip install -r requirements/dev.txt
script:
  - export FLASK_APP=./autoapp.py
  - export FLASK_DEBUG=1
  - npm install npm@">3.0.0"
  - export PATH=$(npm bin):$PATH
  - npm install
  - npm run lint
  - npm run bundle
  - flask lint
  - flask test
